#ifndef VESTIGIO_CGLTF_NAMESPACE_H
#define VESTIGIO_CGLTF_NAMESPACE_H

/* raylib also embeds cgltf with global symbols. Prefix Vestigio's private copy
 * so the importer and renderer can coexist in one executable. */
#define cgltf_parse vg_cgltf_parse
#define cgltf_parse_file vg_cgltf_parse_file
#define cgltf_load_buffers vg_cgltf_load_buffers
#define cgltf_load_buffer_base64 vg_cgltf_load_buffer_base64
#define cgltf_decode_string vg_cgltf_decode_string
#define cgltf_decode_uri vg_cgltf_decode_uri
#define cgltf_validate vg_cgltf_validate
#define cgltf_free vg_cgltf_free
#define cgltf_node_transform_local vg_cgltf_node_transform_local
#define cgltf_node_transform_world vg_cgltf_node_transform_world
#define cgltf_buffer_view_data vg_cgltf_buffer_view_data
#define cgltf_find_accessor vg_cgltf_find_accessor
#define cgltf_accessor_read_float vg_cgltf_accessor_read_float
#define cgltf_accessor_read_uint vg_cgltf_accessor_read_uint
#define cgltf_accessor_read_index vg_cgltf_accessor_read_index
#define cgltf_num_components vg_cgltf_num_components
#define cgltf_component_size vg_cgltf_component_size
#define cgltf_calc_size vg_cgltf_calc_size
#define cgltf_accessor_unpack_floats vg_cgltf_accessor_unpack_floats
#define cgltf_accessor_unpack_indices vg_cgltf_accessor_unpack_indices
#define cgltf_copy_extras_json vg_cgltf_copy_extras_json
#define cgltf_mesh_index vg_cgltf_mesh_index
#define cgltf_material_index vg_cgltf_material_index
#define cgltf_accessor_index vg_cgltf_accessor_index
#define cgltf_buffer_view_index vg_cgltf_buffer_view_index
#define cgltf_buffer_index vg_cgltf_buffer_index
#define cgltf_image_index vg_cgltf_image_index
#define cgltf_texture_index vg_cgltf_texture_index
#define cgltf_sampler_index vg_cgltf_sampler_index
#define cgltf_skin_index vg_cgltf_skin_index
#define cgltf_camera_index vg_cgltf_camera_index
#define cgltf_light_index vg_cgltf_light_index
#define cgltf_node_index vg_cgltf_node_index
#define cgltf_scene_index vg_cgltf_scene_index
#define cgltf_animation_index vg_cgltf_animation_index
#define cgltf_animation_sampler_index vg_cgltf_animation_sampler_index
#define cgltf_animation_channel_index vg_cgltf_animation_channel_index

#endif
